Repository openshift-knative/deviate, pull requests merged in 2025-06, with the labels that each got.

#39 only trigger CI if syncCi is set
  pkg/config/defaults.go
  pkg/config/structure.go
  pkg/sync/create_pr.go
  pkg/sync/resync_releases.go
  pkg/sync/trigger_ci.go
Labels: approved, lgtm

#38 fix: Ensure that remote "downstream" is available
  pkg/git/push_prelease.go
Labels: approved, lgtm

#48 :lady_beetle: Skip check PRs ob a flag
  pkg/config/defaults.go
  pkg/config/structure.go
  pkg/sync/create_pr.go
  pkg/sync/resync_releases.go
  pkg/sync/trigger_ci.go
Labels: kind/bug, approved, lgtm

#45 :gift: Copy/Delete filters
  go.mod
  go.sum
  pkg/config/defaults.go
  pkg/config/git/checkout.go
  pkg/config/structure.go
  pkg/files/delete_by_filters.go
  pkg/files/delete_by_filters_test.go
  pkg/files/filters.go
  pkg/files/filters_test.go
  pkg/git/checkout.go
  pkg/git/checkout_test.go
  pkg/sync/fork_files.go
  pkg/sync/remove_github_workflows.go
  pkg/sync/remove_unwanted_upstream_files.go
Labels: kind/enhancement, approved, lgtm
